package com.itsjeel01.finsiblefrontend.ui.theme

import androidx.compose.ui.graphics.Color

data class FinsibleColors(
    val transparent: Color = Color.Companion.Transparent,
    val black: Color = Color(0xFF000000),
    val white: Color = Color(0xFFFFFFFF),
    val same: Color,
    val inverse: Color,
    val primaryBackground: Color,
    val secondaryBackground: Color,
    val primaryContent: Color,
    val primaryContent80: Color = primaryContent.copy(alpha = 0.8f),
    val primaryContent60: Color = primaryContent.copy(alpha = 0.6f),
    val primaryContent40: Color = primaryContent.copy(alpha = 0.4f),
    val primaryContent20: Color = primaryContent.copy(alpha = 0.2f),
    val secondaryContent: Color,
    val hover: Color,
    val disabled: Color,
    val border: Color,
    val card: Color,
    val input: Color,
    val primaryButton: Color,
    val secondaryButton: Color,
    val link: Color,
    val selection: Color,
    val shadow: Color,
    val overlay: Color,
    val error: Color,
    val success: Color,
    val warning: Color,
    val brandAccent: Color = Color(0xFF2E8B57),
    val brandAccent90: Color,
    val brandAccent80: Color,
    val brandAccent70: Color,
    val brandAccent60: Color,
    val brandAccent50: Color,
    val brandAccent40: Color,
    val brandAccent30: Color,
    val brandAccent20: Color,
    val brandAccent10: Color,
) {
    companion object {
        val light = FinsibleColors(
            inverse = Color(0xFF000000),
            same = Color(0xFFFFFFFF),
            primaryBackground = Color(0xFFFEFEFA),
            secondaryBackground = Color(0xFFF8F8F4),
            primaryContent = Color(0xFF010B13),
            secondaryContent = Color(0xFF4A4A4A),
            hover = Color(0xFFE8F5E8),
            disabled = Color(0xFFBDBDBD),
            border = Color(0xFFE5E5E1),
            card = Color(0xFFFFFFFF),
            input = Color(0xFFFBFBF7),
            primaryButton = Color(0xFF2E8B57),
            secondaryButton = Color(0xFFF8F8F4),
            link = Color(0xFF1B5E20),
            selection = Color(0xFFC8E6C9),
            shadow = Color(0x26010B13),
            overlay = Color(0x99010B13),
            error = Color(0xFFD72D25),
            success = Color(0xFF03C03C),
            warning = Color(0xFFFFBF00),
            brandAccent = Color(0xFF2E8B57),
            brandAccent90 = Color(0xFF3AAD6B),
            brandAccent80 = Color(0xFF3FBE76),
            brandAccent70 = Color(0xFF50C583),
            brandAccent60 = Color(0xFF73D09C),
            brandAccent50 = Color(0xFF96DCB4),
            brandAccent40 = Color(0xFFB9E8CD),
            brandAccent30 = Color(0xFFCBEEDA),
            brandAccent20 = Color(0xFFDCF3E6),
            brandAccent10 = Color(0xFFEEF9F3),
        )

        val dark = FinsibleColors(
            inverse = Color(0xFFFFFFFF),
            same = Color(0xFF000000),
            primaryBackground = Color(0xFF1B1B1B),
            secondaryBackground = Color(0xFF242424),
            primaryContent = Color(0xFFF7F7F7),
            secondaryContent = Color(0xFFB8B8B8),
            hover = Color(0xFF1F3A2B),
            disabled = Color(0xFF525252),
            border = Color(0xFF404040),
            card = Color(0xFF2A2A2A),
            input = Color(0xFF1F1F1F),
            primaryButton = Color(0xFF2E8B57),
            secondaryButton = Color(0xFF404040),
            link = Color(0xFF4CAF50),
            selection = Color(0xFF1F3A2B),
            shadow = Color(0x40000000),
            overlay = Color(0xB3000000),
            error = Color(0xFFFF513E),
            success = Color(0xFF03C03C),
            warning = Color(0xFFFFBF00),
            brandAccent = Color(0xFF5BB95E),
            brandAccent90 = Color(0xFF277649),
            brandAccent80 = Color(0xFF246C43),
            brandAccent70 = Color(0xFF21623D),
            brandAccent60 = Color(0xFF1E5937),
            brandAccent50 = Color(0xFF1A4F31),
            brandAccent40 = Color(0xFF143B25),
            brandAccent30 = Color(0xFF10311F),
            brandAccent20 = Color(0xFF0A1E12),
            brandAccent10 = Color(0xFF07140C),
        )
    }
}